# Generated by Django 6.0.7 on 2026-08-30 04:35

import django.db.models.deletion
import pilgrims.storage
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_sacredsitepage_canonical_status'),
        ('pilgrims', '0003_migrate_from_community'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilgrimPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('taken_on', models.DateField(blank=True, null=True)),
                ('original', models.FileField(max_length=255, storage=pilgrims.storage.get_pilgrim_private_storage, upload_to='')),
                ('large', models.ImageField(max_length=255, storage=pilgrims.storage.get_pilgrim_private_storage, upload_to='')),
                ('feed', models.ImageField(max_length=255, storage=pilgrims.storage.get_pilgrim_private_storage, upload_to='')),
                ('thumb', models.ImageField(max_length=255, storage=pilgrims.storage.get_pilgrim_private_storage, upload_to='')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('byte_size', models.PositiveIntegerField()),
                ('content_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public_on_site', models.BooleanField(default=False)),
                ('public_shared_at', models.DateTimeField(blank=True, null=True)),
                ('public_credit', models.CharField(blank=True, choices=[('display_name', 'My display name'), ('first_name_only', 'First name only'), ('anonymous', 'Anonymous')], max_length=20)),
                ('public_large', models.ImageField(blank=True, null=True, upload_to='')),
                ('public_thumb', models.ImageField(blank=True, null=True, upload_to='')),
                ('hidden_by_staff', models.BooleanField(default=False)),
                ('hidden_reason', models.CharField(blank=True, max_length=255)),
                ('hidden_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilgrim_photos', to='catalog.sacredsitepage')),
            ],
            options={
                'ordering': ['-taken_on', '-created_at'],
                'indexes': [models.Index(fields=['owner', 'site'], name='pilgrims_pi_owner_i_4fa6c6_idx'), models.Index(fields=['site', 'is_public_on_site', 'hidden_by_staff'], name='pilgrims_pi_site_id_1b57ed_idx')],
            },
        ),
    ]
