# Generated by Django 6.0.7 on 2026-09-03 03:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_sacredsitepage_canonical_status'),
        ('pilgrims', '0005_post_comment_postphoto_notification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'created_at'], name='pilgrims_co_author__a33c27_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower', 'created_at'], name='pilgrims_fo_followe_0c214d_idx'),
        ),
        migrations.AddIndex(
            model_name='pilgrimphoto',
            index=models.Index(fields=['owner', 'created_at'], name='pilgrims_pi_owner_i_fb7a3a_idx'),
        ),
    ]
