# Generated by Django 6.0.7 on 2026-09-03 03:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pilgrims', '0006_comment_pilgrims_co_author__a33c27_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrimprofile',
            name='can_share_publicly',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='PhotoReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reporter_ip_hash', models.CharField(max_length=64)),
                ('reason', models.CharField(choices=[('sexual', 'Sexual content'), ('minor_safety', 'Minor safety'), ('violence', 'Violence'), ('hateful', 'Hateful content'), ('copyright', 'Copyright'), ('not_this_site', 'Not actually this site'), ('other', 'Other')], max_length=20)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='open', max_length=10)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='pilgrims.pilgrimphoto')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('view_reported_photo', 'Viewed reported photo'), ('hide', 'Hid photo'), ('unhide', 'Unhid photo'), ('dismiss_report', 'Dismissed report'), ('delete_photo', 'Deleted photo'), ('suspend_sharing', "Suspended owner's public sharing"), ('reinstate_sharing', "Reinstated owner's public sharing")], max_length=30)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_actions', to=settings.AUTH_USER_MODEL)),
                ('owner_affected', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='pilgrims.pilgrimphoto')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_actions', to='pilgrims.photoreport')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='photoreport',
            index=models.Index(fields=['photo', 'status'], name='pilgrims_ph_photo_i_ef615c_idx'),
        ),
        migrations.AddIndex(
            model_name='photoreport',
            index=models.Index(fields=['reporter_ip_hash', 'created_at'], name='pilgrims_ph_reporte_cedab9_idx'),
        ),
    ]
