# Generated by Django 6.0.7 on 2026-09-03 04:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_sacredsitepage_canonical_status'),
        ('pilgrims', '0007_pilgrimprofile_can_share_publicly_photoreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pilgrimphoto',
            index=models.Index(fields=['owner', 'public_shared_at'], name='pilgrims_pi_owner_i_dc6731_idx'),
        ),
    ]
