# Generated by Django 6.0.7 on 2026-07-30 22:13

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amazon_associate_tag', models.CharField(blank=True, max_length=60)),
                ('affiliate_disclosure', wagtail.fields.RichTextField(blank=True, default='<p>As an Amazon Associate, we earn from qualifying purchases.</p>')),
                ('store_intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Store settings',
            },
        ),
        migrations.CreateModel(
            name='StoreProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Author, artist, or brand', max_length=200)),
                ('category', models.CharField(choices=[('Books', 'Books'), ('Films', 'Films'), ('Devotionals & Sacramentals', 'Devotionals & Sacramentals'), ('Clothing', 'Clothing'), ('Gifts', 'Gifts')], max_length=40)),
                ('kind', models.CharField(choices=[('affiliate', 'Affiliate (Amazon / external)'), ('own', 'Our own product')], default='affiliate', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('amazon_asin', models.CharField(blank=True, help_text='Amazon ASIN (e.g. B0XXXXXXX). Builds a tagged affiliate link.', max_length=20)),
                ('link_url', models.URLField(blank=True, help_text="Used when there's no ASIN: an external affiliate URL, or the checkout URL for our own products.")),
                ('price', models.CharField(blank=True, help_text='Only shown for our own products, e.g. $24.99. Leave blank for Amazon items (price shows on Amazon).', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Show on the homepage band.')),
                ('sort_order', models.IntegerField(default=0)),
                ('live', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
