# Generated by Django 6.0.7 on 2026-08-10 19:46

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storeindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='cta_mode',
            field=models.CharField(choices=[('link', 'Link (Link URL / Amazon)'), ('waitlist', 'Waitlist (collects an email, no payment)')], default='link', help_text='Waitlist collects an email instead of linking out -- no payment is taken.', max_length=10),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='fine_print',
            field=models.CharField(blank=True, help_text='Shipping and renewal terms shown under the buttons.', max_length=300),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='layout',
            field=models.CharField(choices=[('card', 'Card (grid)'), ('feature', 'Feature (full-width)')], default='card', max_length=10),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='long_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Shown only in feature layout.'),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='ribbon_text',
            field=models.CharField(blank=True, help_text='e.g. "Quarterly Subscription", "New for 2027"', max_length=60),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='spotlight_note',
            field=models.CharField(blank=True, help_text='e.g. "Shipping the first week of October"', max_length=120),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='spotlight_title',
            field=models.CharField(blank=True, help_text='e.g. "Autumn 2026 · Lourdes, France"', max_length=120),
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Films', 'Films'), ('Devotionals & Sacramentals', 'Devotionals & Sacramentals'), ('Clothing', 'Clothing'), ('Gifts', 'Gifts'), ('Subscriptions', 'Subscriptions'), ('Calendars & Planners', 'Calendars & Planners')], max_length=40),
        ),
        migrations.CreateModel(
            name='ProductInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('lead_in', models.CharField(blank=True, help_text='Bolded opening phrase, e.g. "A blessed rosary"', max_length=60)),
                ('text', models.CharField(max_length=200)),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='store.storeproduct')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductPriceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='e.g. "Full Year · 4 boxes"', max_length=60)),
                ('amount', models.CharField(help_text='e.g. "$196"', max_length=20)),
                ('unit', models.CharField(blank=True, help_text='e.g. "/yr"', max_length=20)),
                ('note', models.CharField(blank=True, help_text='e.g. "Save $20"', max_length=60)),
                ('is_default', models.BooleanField(default=False)),
                ('product', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_options', to='store.storeproduct')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WaitlistSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_signups', to='store.storeproduct')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('product', 'email')},
            },
        ),
    ]
