# Generated by Django 6.0.7 on 2026-08-10 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('feed_url', models.URLField()),
                ('enabled', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('last_fetched', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField(help_text='Hard-truncated to ~200 chars at a word boundary by the fetcher.')),
                ('link', models.URLField()),
                ('guid', models.CharField(help_text="Dedupe key from the feed's <guid>, falling back to the link.", max_length=500, unique=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('image_url', models.URLField(blank=True, help_text='Only set when the feed supplies a media/enclosure URL.')),
                ('topic', models.CharField(choices=[('shrines', 'Shrines & Sites'), ('events', 'Events & Festivals'), ('pilgrimage', 'Pilgrimage'), ('saints', 'Saints & Causes'), ('general', 'General')], default='general', max_length=20)),
                ('hidden', models.BooleanField(default=False, help_text='Suppress this item from the site without deleting it.')),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='news.newssource')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
