# Generated by Django 6.0.7 on 2026-08-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_seed_news_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image_url',
            field=models.URLField(blank=True, help_text='Only set when the feed supplies a media/enclosure URL.', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
