# Generated by Django 6.0.7 on 2026-07-14 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(blank=True, default='Discover the sacred places where heaven has touched earth.', max_length=180)),
                ('footer_summary', models.TextField(blank=True, default="Sites of Grace is a Catholic pilgrimage and sacred-sites reference: explore Marian apparitions, Eucharistic miracles, saints' tombs, shrines, and Holy Land destinations around the world.")),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True, verbose_name='X (Twitter) URL')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('newsletter_heading', models.CharField(blank=True, default='Stay inspired on your journey.', max_length=120)),
                ('newsletter_text', models.CharField(blank=True, default='Sacred-site spotlights, Catholic teaching, and pilgrimage ideas each week.', max_length=240)),
                ('disclaimer', models.TextField(blank=True, default='Sites of Grace is an independent educational Catholic resource and does not speak officially on behalf of the Catholic Church, any diocese, shrine, or religious community. Church status information should be verified through official diocesan or Vatican sources whenever possible.')),
                ('logo', models.ForeignKey(blank=True, help_text='Header/footer logo. Leave blank to fall back to the text wordmark.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'verbose_name': 'Site settings',
            },
        ),
    ]
