# Generated by Django 6.0.7 on 2026-07-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_update_newsletter_copy'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='newsletter_text',
            field=models.CharField(blank=True, default='Receive sacred site spotlights, Catholic teaching, pilgrimage ideas, and prayers each week.', max_length=240),
        ),
    ]
