# Generated by Django 6.0.7 on 2026-07-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_journeyentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilgrimprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
