# Generated by Django 6.0.7 on 2026-10-02 20:55

import datetime
import django.db.models.deletion
import modelcluster.fields
import wagtail.contrib.routable_page.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, help_text="Shown under the heading on this category's page.")),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers come first in the category chips.')),
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(default="From the Pilgrim's Desk", max_length=60)),
                ('intro', models.TextField(default='Stories of sacred places, practical pilgrimage travel guides, and the saints who made these places holy.')),
                ('posts_per_page', models.PositiveSmallIntegerField(default=12)),
            ],
            options={
                'verbose_name': 'Blog index page',
            },
            bases=(wagtail.contrib.routable_page.models.RoutablePageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='BlogPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(default=datetime.date.today, help_text='Shown on the post. Posts are ordered newest first by this date.')),
                ('author_name', models.CharField(default='Steven Fyffe', max_length=80)),
                ('excerpt', models.TextField(help_text='One or two sentences. Used on blog cards, in search results, and as the description in link previews.', max_length=300)),
                ('body', wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 5), ('quote', 7), ('embed', 8), ('callout', 11), ('site_link', 13)], blank=True, block_lookup={0: ('blog.models.HeadingBlock', (), {}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'h3', 'blockquote'], 'template': 'blog/blocks/paragraph.html'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'required': False}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('column', 'Column width'), ('wide', 'Wide')]}), 5: ('wagtail.blocks.StructBlock', [[('image', 2), ('caption', 3), ('width', 4)]], {}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('text', 6), ('attribution', 3)]], {}), 8: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'template': 'blog/blocks/embed.html'}), 9: ('wagtail.blocks.CharBlock', (), {}), 10: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul']}), 11: ('wagtail.blocks.StructBlock', [[('title', 9), ('text', 10)]], {}), 12: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['catalog.SacredSitePage', 'catalog.SaintPage']}), 13: ('wagtail.blocks.StructBlock', [[('page', 12), ('note', 3)]], {})})),
                ('categories', modelcluster.fields.ParentalManyToManyField(related_name='posts', to='blog.blogcategory')),
                ('feature_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog post',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPostRelatedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('post', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_pages', to='blog.blogpostpage')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='Place, saint, or trail')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
