# Generated by Django 6.0.7 on 2026-07-14 19:40

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='Every pin is a sacred site. Filter by category, then open a site to read its story.')),
            ],
            options={
                'verbose_name': 'Interactive map page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StandardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Standard page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='StorePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, default='Prayer resources, study guides, and pilgrimage keepsakes — coming soon.')),
                ('body', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'verbose_name': 'Store page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home page'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, default='Discover sacred places. Track your journey. Deepen your faith.', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_intro',
            field=models.TextField(blank=True, default="Explore Marian apparitions, Eucharistic miracles, saints' tombs, sacred shrines, and Catholic pilgrimage destinations around the world."),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_cta_link',
            field=models.CharField(blank=True, default='/interactive-map/', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='primary_cta_text',
            field=models.CharField(blank=True, default='Explore the Map', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_cta_link',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='secondary_cta_text',
            field=models.CharField(blank=True, default='Begin Your Journey', max_length=40),
        ),
    ]
