# Generated by Django 6.0.7 on 2026-07-16 16:56

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mappage_standardpage_storepage_and_more'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='community_cta_link',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_cta_text',
            field=models.CharField(blank=True, default='Begin Your Journey', max_length=40),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_heading',
            field=models.CharField(blank=True, default='Your Journey, Your Story', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='community_intro',
            field=models.TextField(blank=True, default='Create your personal pilgrim profile, track the sacred places you have visited, save future destinations, and share the moments that deepened your faith.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_saints_heading',
            field=models.CharField(blank=True, default='Featured Saints', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_sites_heading',
            field=models.CharField(blank=True, default='Featured Sacred Sites', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partners_heading',
            field=models.CharField(blank=True, default='Pilgrimage Partners', max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partners_quote',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='partners_quote_source',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='homepage',
            name='store_heading',
            field=models.CharField(blank=True, default='Books, Films & More', max_length=80),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, default='Discover sacred places. Track your journey. Deepen your faith.', max_length=160),
        ),
        migrations.CreateModel(
            name='FeatureCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=80)),
                ('blurb', models.TextField(blank=True)),
                ('link_url', models.CharField(blank=True, help_text='Used only if no page is chosen.', max_length=255)),
                ('link_text', models.CharField(blank=True, default='Learn More', max_length=40)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_cards', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedSaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title_override', models.CharField(blank=True, max_length=120)),
                ('image_override', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_saints', to='home.homepage')),
                ('saint_page', models.ForeignKey(blank=True, help_text='Choose the saint page to feature.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeaturedSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title_override', models.CharField(blank=True, help_text='Optional. Defaults to the page title.', max_length=120)),
                ('image_override', models.ForeignKey(blank=True, help_text="Optional. Falls back to the site page's own image once available.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_sites', to='home.homepage')),
                ('site_page', models.ForeignKey(blank=True, help_text='Choose the sacred site page to feature.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JourneyBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=80)),
                ('text', models.CharField(blank=True, max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_bullets', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StorePick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('price', models.CharField(blank=True, max_length=20)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('cover', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_picks', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
