# Generated by Django 6.0.7 on 2026-07-21 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_community_cta_link_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardpage',
            name='card_image',
            field=models.ForeignKey(blank=True, help_text='Optional. Falls back to a branded color placeholder if not set.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='layout',
            field=models.CharField(choices=[('default', 'Default'), ('explore_hub', 'Explore hub (category card grid)'), ('category_directory', 'Category directory (site card grid)'), ('saints_directory', 'Saints directory (saint card grid)')], default='default', max_length=30),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='teaser',
            field=models.CharField(blank=True, help_text="One-line description shown on this page's card when it's linked from a hub page.", max_length=200),
        ),
    ]
