# Generated by Django 6.0.7 on 2026-07-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_update_homepage_copy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='community_cta_link',
            field=models.CharField(blank=True, default='/accounts/signup/', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='community_intro',
            field=models.TextField(blank=True, default='Create your personal pilgrim profile, track the sacred places you have visited, save future destinations, upload photos, and share the moments that deepened your faith.'),
        ),
    ]
