# Generated by Django 6.0.7 on 2026-08-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_community_cta_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='news_count',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_heading',
            field=models.CharField(blank=True, default='News from the Sacred Places', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_intro',
            field=models.TextField(blank=True, default='Shrine announcements, pilgrimage news, feast celebrations, and events — from trusted Catholic newsrooms.'),
        ),
    ]
