# Generated by Django 6.0.7 on 2026-08-26 17:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_homepage_news_count_homepage_news_enabled_and_more"),
        ("store", "0004_seed_own_brand_products"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="featured_saints_heading",
        ),
        migrations.AddField(
            model_name="homepage",
            name="subscription_cta_link",
            field=models.CharField(
                blank=True,
                default="/store/",
                help_text="Where the button goes when no product is chosen above.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subscription_cta_text",
            field=models.CharField(
                blank=True, default="Join the Waitlist", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subscription_heading",
            field=models.CharField(
                blank=True,
                default="Pilgrimage From Home",
                help_text="Small heading across the top of the bucket.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subscription_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Large image for the bucket. Use a tall/portrait crop — it is displayed the same way as the Your Journey photo.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subscription_intro",
            field=models.TextField(
                blank=True,
                default="Four times a year a package arrives from a different holy place — real devotionals sourced from the shrine itself, with a letter that tells the story behind them.",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subscription_price_line",
            field=models.CharField(
                blank=True, default="$54 a quarter · cancel anytime", max_length=80
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subscription_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. Choose the subscription product to show its email waitlist form right here on the homepage. Leave blank to show a plain button instead.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="store.storeproduct",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="subscription_title",
            field=models.CharField(
                blank=True,
                default="The Pilgrim's Box",
                help_text="Name of the subscription, shown large under the image.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="featured_sites_heading",
            field=models.CharField(
                blank=True,
                default="Featured Sites and Saints",
                help_text="Heading for the combined sites + saints bucket at the left of the pilgrim band.",
                max_length=80,
            ),
        ),
        migrations.CreateModel(
            name="SubscriptionBullet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("text", models.CharField(max_length=120)),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_bullets",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
