# Generated by Django 6.0.7 on 2026-09-30 03:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_subscription_copy'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_eyebrow', models.CharField(blank=True, default='Our Mission', max_length=60)),
                ('hero_title', models.CharField(blank=True, default='Helping People Discover the Places Where Faith Comes Alive', max_length=120)),
                ('hero_intro', models.TextField(blank=True, default='Sites of Grace was created to help Catholics and fellow pilgrims discover the sacred places, extraordinary stories, and holy people that have shaped the Church — and to make experiencing those places easier for everyone.')),
                ('hero_cta_label', models.CharField(blank=True, default='Explore Sacred Sites', max_length=40)),
                ('why_eyebrow', models.CharField(blank=True, default='Why Sites of Grace Exists', max_length=60)),
                ('why_title', models.CharField(blank=True, default='Connecting People With Sacred Places', max_length=120)),
                ('why_body', wagtail.fields.RichTextField(blank=True, default='<p>Sites of Grace exists to connect people with the places where generations of Catholics have encountered God in extraordinary ways.</p><p>From Marian apparition sites and Eucharistic miracles to the tombs of saints, ancient churches, pilgrimage routes, and sacred places throughout the world, our goal is to make these destinations easier to discover, understand, and experience.</p><p>But Sites of Grace is about more than travel. It is about helping people understand why these places matter — the stories behind them, the people whose lives were changed there, and the faith that continues to draw pilgrims centuries later.</p>')),
                ('pillars', wagtail.fields.StreamField([('pillar', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('globe', 'Globe'), ('book', 'Book'), ('map', 'Map'), ('camera', 'Camera'), ('church', 'Church'), ('cross', 'Cross'), ('heart', 'Heart')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('text', 2)]], {})}, default=[{'type': 'pillar', 'value': {'icon': 'globe', 'text': 'Find sacred sites around the world.', 'title': 'Discover'}}, {'type': 'pillar', 'value': {'icon': 'book', 'text': 'Understand the history, miracles, saints, and traditions connected to them.', 'title': 'Learn'}}, {'type': 'pillar', 'value': {'icon': 'map', 'text': 'Use practical pilgrimage guides to plan meaningful visits.', 'title': 'Prepare'}}, {'type': 'pillar', 'value': {'icon': 'camera', 'text': 'Record the places you have visited and the experiences you encountered along the way.', 'title': 'Remember'}}])),
                ('began_eyebrow', models.CharField(blank=True, default='How It Began', max_length=60)),
                ('began_title', models.CharField(blank=True, default='A Pilgrimage That Changed Everything', max_length=120)),
                ('began_body', wagtail.fields.RichTextField(blank=True, default='<p>Sites of Grace began with a pilgrimage.</p><p>What started as a journey to pray for someone deeply loved became something much larger — a realization that there are extraordinary places throughout the world where people have traveled for generations seeking healing, peace, conversion, and a deeper relationship with God.</p><p>Along the way, I discovered how difficult it could be to find all of that information in one place. The history might be on one website, Mass times on another, travel information somewhere else, and some of the most meaningful stories were difficult to find at all.</p><p>I began imagining a place where a pilgrim could discover a sacred site, understand its story, prepare for the journey, and carry that experience with them afterward. That idea became Sites of Grace.</p>')),
                ('founder_eyebrow', models.CharField(blank=True, default='About the Founder', max_length=60)),
                ('founder_name', models.CharField(blank=True, default='Steven Fyffe', max_length=120)),
                ('founder_role', models.CharField(blank=True, default='Founder, Sites of Grace', max_length=120)),
                ('founder_bio', wagtail.fields.RichTextField(blank=True, default="<p>Steven created Sites of Grace after his own journey of discovering the Catholic faith and experiencing firsthand the power of pilgrimage.</p><p>His travels to sacred places — including Marian shrines, historic churches, and sites connected with the saints — sparked a desire to create a resource that could help others experience these places with greater understanding and purpose.</p><p>Sites of Grace grew from a simple idea: if someone feels called to visit a sacred place, finding its story and planning the journey shouldn't be difficult.</p>")),
                ('believe_eyebrow', models.CharField(blank=True, default='What We Believe', max_length=60)),
                ('believe_heading', models.TextField(blank=True, default='Pilgrimage Is More Than Going Somewhere.\nIt Is Allowing the Journey to Change You.', help_text='A line break here renders as a line break on the page.')),
                ('believe_body', wagtail.fields.RichTextField(blank=True, default='<p>For centuries, Christians have left the familiarity of home to journey toward sacred places. They traveled carrying prayers, gratitude, questions, sorrow, and hope.</p><p>Sometimes the destination is across the world. Sometimes it is a shrine an hour from home. What matters is the intention with which the journey begins.</p>', help_text='Two paragraphs. The gold emphasis line below is rendered between them.')),
                ('believe_emphasis', models.CharField(blank=True, default='We believe pilgrimage still matters.', max_length=120)),
                ('becoming_eyebrow', models.CharField(blank=True, default='What Sites of Grace Is Becoming', max_length=60)),
                ('becoming_cards', wagtail.fields.StreamField([('card', 5)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 80}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.CharBlock', (), {'max_length': 40}), 4: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('image', 0), ('title', 1), ('text', 2), ('link_label', 3), ('link_page', 4)]], {})}, default=[{'type': 'card', 'value': {'link_label': 'Open the map', 'text': 'Marian apparitions, Eucharistic miracles, saints, shrines, churches, missions, and other places of Catholic significance.', 'title': 'Explore Sacred Places'}}, {'type': 'card', 'value': {'link_label': 'See the guides', 'text': 'Practical travel guides, itineraries, Mass and confession information, accessibility guidance, lodging, transportation, and local recommendations.', 'title': 'Plan Your Pilgrimage'}}, {'type': 'card', 'value': {'link_label': 'Start your passport', 'text': 'Track the sites you have visited, save photographs, preserve memories, and share your experiences with other pilgrims.', 'title': 'Create Your Pilgrim Story'}}])),
                ('closing_title', models.CharField(blank=True, default='Where Will Your Journey Begin?', max_length=120)),
                ('closing_text', models.TextField(blank=True, default='There are thousands of sacred places throughout the world, each carrying a story of faith worth discovering.')),
                ('closing_primary_label', models.CharField(blank=True, default='Explore Sites', max_length=40)),
                ('closing_secondary_label', models.CharField(blank=True, default='Learn About Pilgrimage', max_length=40)),
                ('began_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('believe_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('closing_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('closing_primary_page', models.ForeignKey(blank=True, help_text='Optional. Falls back to the interactive map / Explore hub if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('closing_secondary_page', models.ForeignKey(blank=True, help_text='Optional. No fallback -- the button is hidden until a page is chosen here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('founder_photo', models.ForeignKey(blank=True, help_text='Brand editorial portrait, not a pilgrim-submitted photo. Renders arched.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('hero_cta_page', models.ForeignKey(blank=True, help_text='Optional. Falls back to the interactive map / Explore hub if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Our Story page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
