# Generated by Django 6.0.7 on 2026-10-06 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_aboutpage'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='calendar_enabled',
            field=models.BooleanField(default=True, help_text="Show today's liturgical calendar card in the pilgrim band."),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calendar_footer_link',
            field=models.ForeignKey(blank=True, help_text='Optional. Falls back to the saints directory.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calendar_footer_link_text',
            field=models.CharField(blank=True, default='Browse saints by feast day', max_length=60),
        ),
        migrations.AddField(
            model_name='homepage',
            name='calendar_heading',
            field=models.CharField(blank=True, default='Today in the Church', max_length=60),
        ),
    ]
