# Generated by Django 6.0.7 on 2026-10-07 18:44

import django.core.validators
import django.db.models.deletion
import home.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_homepage_today_in_church'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_eyebrow', models.CharField(blank=True, default='Support Sites of Grace', max_length=60)),
                ('hero_title', models.CharField(blank=True, default='Help Keep the Way Open', max_length=120)),
                ('hero_intro', models.TextField(blank=True, default='Sites of Grace helps Catholics discover the holy places of our faith, learn their stories, and plan meaningful pilgrimages. It is free to use, and it always will be.')),
                ('why_eyebrow', models.CharField(blank=True, default='Why We Ask', max_length=60)),
                ('why_heading', models.CharField(blank=True, default='Independently Built, Freely Shared', max_length=120)),
                ('why_body', wagtail.fields.RichTextField(blank=True, default="<p>Sites of Grace is built and maintained independently. Every map, saint's story, and pilgrimage guide is offered free of charge, and nothing on the site is locked behind a payment.</p><p>If Sites of Grace has helped you find a new pilgrimage site, plan a journey, or simply learn more about the faith, you're welcome to help support its continued growth. There's no obligation, and every pilgrim is welcome here either way.</p>")),
                ('pull_quote', models.CharField(blank=True, default='“Freely you have received; freely give.”', max_length=200)),
                ('pull_quote_cite', models.CharField(blank=True, default='Matthew 10:8', max_length=80)),
                ('helps_eyebrow', models.CharField(blank=True, default='What Your Support Helps With', max_length=60)),
                ('helps', wagtail.fields.StreamField([('help', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('globe', 'Globe'), ('book', 'Book'), ('map', 'Map'), ('camera', 'Camera'), ('church', 'Church'), ('cross', 'Cross'), ('heart', 'Heart'), ('server', 'Server'), ('document', 'Document'), ('pin', 'Map pin'), ('share', 'Share'), ('pencil', 'Pencil'), ('bookmark', 'Bookmark'), ('candle', 'Candle')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 2: ('wagtail.blocks.TextBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('blurb', 2)]], {})}, default=[{'type': 'help', 'value': {'blurb': 'Keeping the site fast, secure, and available to pilgrims around the world.', 'icon': 'server', 'title': 'Hosting & Upkeep'}}, {'type': 'help', 'value': {'blurb': 'Checking every site and saint against Church and shrine sources.', 'icon': 'document', 'title': 'Research'}}, {'type': 'help', 'value': {'blurb': 'Better maps, original photos, and more places on the map.', 'icon': 'map', 'title': 'Maps & Photography'}}, {'type': 'help', 'value': {'blurb': 'Plan Your Visit guides and trails for more sacred sites.', 'icon': 'pin', 'title': 'New Pilgrimage Guides'}}])),
                ('give_heading', models.CharField(blank=True, default='Support Sites of Grace', max_length=120)),
                ('give_lede', models.CharField(blank=True, default="Choose an amount. You'll finish on Stripe's secure checkout page.", max_length=200)),
                ('preset_amounts', models.CharField(default='5,10,25,50', help_text='1 to 6 whole-dollar amounts, separated by commas. An "Other" tile is always added.', max_length=60)),
                ('min_amount', models.IntegerField(default=3, help_text='Smallest amount accepted, in whole dollars.', validators=[django.core.validators.MinValueValidator(1)])),
                ('max_amount', models.IntegerField(default=1000, help_text='Largest amount accepted, in whole dollars.', validators=[django.core.validators.MinValueValidator(1)])),
                ('default_amount_once', models.IntegerField(default=10, help_text='Preselected for one-time support. Must be one of the amounts above.')),
                ('default_amount_monthly', models.IntegerField(default=5, help_text='Preselected for monthly support. Must be one of the amounts above.')),
                ('allow_monthly', models.BooleanField(default=True)),
                ('disclaimer', models.TextField(default='Sites of Grace is independently owned and is not a 501(c)(3) charitable organization. Contributions are voluntary, support the operation of the website, and are not tax-deductible. Nothing is given in exchange, and all content stays free. Monthly support can be cancelled anytime.', help_text='Required. Must say contributions are "not tax-deductible".')),
                ('soon_heading', models.CharField(blank=True, default='Online Support Opens Soon', max_length=120)),
                ('soon_text', models.TextField(blank=True, default="We're setting up secure online support now. Thank you for thinking of us.\n\nIn the meantime, the ways to help on this page cost nothing at all.", help_text='Shown instead of the form until Stripe is configured. A blank line starts a new paragraph.')),
                ('thanks_heading', models.CharField(blank=True, default='Thank You', max_length=120)),
                ('thanks_text', models.TextField(blank=True, default='Your support helps more people discover the extraordinary places of our faith. May the saints keep you on your journey.')),
                ('manage_url', models.URLField(blank=True, help_text='Stripe customer portal login link. The "Manage monthly support" links appear only when this is set.')),
                ('ways_heading', models.CharField(blank=True, default='Other Ways to Help', max_length=120)),
                ('ways_intro', models.CharField(blank=True, default="Some of the most helpful support doesn't cost anything.", max_length=200)),
                ('ways', wagtail.fields.StreamField([('way', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('globe', 'Globe'), ('book', 'Book'), ('map', 'Map'), ('camera', 'Camera'), ('church', 'Church'), ('cross', 'Cross'), ('heart', 'Heart'), ('server', 'Server'), ('document', 'Document'), ('pin', 'Map pin'), ('share', 'Share'), ('pencil', 'Pencil'), ('bookmark', 'Bookmark'), ('candle', 'Candle')]}), 1: ('wagtail.blocks.CharBlock', (), {'max_length': 60}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 3: ('wagtail.blocks.StructBlock', [[('icon', 0), ('title', 1), ('text', 2)]], {})}, default=home.models.default_support_ways)),
                ('free_card_heading', models.CharField(blank=True, default='Always Free', max_length=120)),
                ('free_card_text', models.TextField(blank=True, default='Support never unlocks anything extra. Every map, guide, and story stays open to every pilgrim, whether they give or not.')),
                ('faq_eyebrow', models.CharField(blank=True, default='Good to Know', max_length=60)),
                ('faq_heading', models.CharField(blank=True, default='Common Questions', max_length=120)),
                ('faqs', wagtail.fields.StreamField([('faq', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'max_length': 160}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link']}), 2: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Adds a "Manage your monthly support" link under the answer, only while the page\'s manage URL is set.', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('question', 0), ('answer', 1), ('show_manage_link', 2)]], {})}, default=[{'type': 'faq', 'value': {'answer': "<p>No. Sites of Grace is independently owned and is not a 501(c)(3) charitable organization, so contributions are not tax-deductible. If you'd like to make a tax-deductible gift, please consider your parish or a shrine you love.</p>", 'question': 'Is my contribution tax-deductible?'}}, {'type': 'faq', 'value': {'answer': '<p>The costs of running the site: hosting, research, maps and photography, and new pilgrimage guides. It helps Sites of Grace keep growing while everything stays free to use.</p>', 'question': 'What does my support pay for?'}}, {'type': 'faq', 'value': {'answer': '<p>No. Support is a gift toward the work, not a purchase. Every page, map, and guide is open to everyone.</p>', 'question': 'Do supporters get anything extra?'}}, {'type': 'faq', 'value': {'answer': '<p>You can update your card or cancel anytime. Stripe handles it securely: enter the email you used, and Stripe sends you a link where you can make changes.</p>', 'question': 'How do I change or cancel monthly support?', 'show_manage_link': True}}, {'type': 'faq', 'value': {'answer': '<p>Payments are handled entirely by Stripe, a widely used payment processor. Your card details go straight to Stripe and never pass through or get stored on Sites of Grace.</p>', 'question': 'Is my payment information safe?'}}])),
                ('home_band_text', models.CharField(blank=True, default='Sites of Grace is independently built and free for every pilgrim.', max_length=200)),
                ('home_band_emphasis', models.CharField(blank=True, default='If it has helped you along the way, you can help it grow.', max_length=200)),
                ('show_home_band', models.BooleanField(default=True, help_text='A quiet band at the bottom of the home page, linking here.')),
                ('hero_image', models.ForeignKey(blank=True, help_text='Optional. Without one, the hero uses the brand gradient panel.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Support page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
