"""
Django settings for sitesofgrace project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

# Build paths inside the project like this: BASE_DIR / 'subdir'.
import os
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = PROJECT_DIR.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# Application definition

INSTALLED_APPS = [
    "core",
    "home",
    "learning",
    "search",
    "catalog",
    "pilgrims",
    "planner",
    "store",
    "news",
    "wagtail.contrib.forms",
    "wagtail.contrib.redirects",
    "wagtail.contrib.routable_page",
    "wagtail.contrib.settings",
    "wagtail.embeds",
    "wagtail.sites",
    "wagtail.users",
    "wagtail.snippets",
    "wagtail.documents",
    "wagtail.images",
    "wagtail.search",
    "wagtail.admin",
    "wagtail",
    "modelcluster",
    "taggit",
    "django_filters",
    "wagtailmenus",
    "allauth",
    "allauth.account",
    # Installed (with its migrations applied) but unconfigured — no
    # SOCIALACCOUNT_PROVIDERS yet. Adding Google sign-in later is then a
    # config change, not a migration, because the app's tables already exist.
    "allauth.socialaccount",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.postgres",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.sites",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    # Must stay first (before SecurityMiddleware) so it wraps every real
    # response in every environment, not just production — the /pilgrims/
    # and /accounts/ noindex requirement is permanent, not a deploy-time
    # toggle. production.py prepends HealthCheckMiddleware ahead of this one
    # (see its own MIDDLEWARE comment) so the health probe itself is
    # untouched; nothing else needs to run before it.
    "core.middleware.NoindexMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "allauth.account.middleware.AccountMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "wagtail.contrib.redirects.middleware.RedirectMiddleware",
]

# Shared by core.middleware.HealthCheckMiddleware (bypasses ALLOWED_HOSTS
# validation entirely), core.middleware.SitePrivateMiddleware (exempted from
# the Basic Auth gate), settings/production.py's SECURE_REDIRECT_EXEMPT, and
# the URL route below — one source of truth so they can't drift apart.
HEALTH_CHECK_PATH = "/health/"

ROOT_URLCONF = "sitesofgrace.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            PROJECT_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "wagtail.contrib.settings.context_processors.settings",
                "wagtailmenus.context_processors.wagtailmenus",
            ],
        },
    },
]

WSGI_APPLICATION = "sitesofgrace.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.environ.get("DB_NAME", "sitesofgrace"),
        "USER": os.environ.get("DB_USER", "sog"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", "127.0.0.1"),
        "PORT": os.environ.get("DB_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# django.contrib.sites is required by allauth
SITE_ID = 1

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

LOGIN_REDIRECT_URL = "/pilgrims/"
LOGOUT_REDIRECT_URL = "/"

# django-allauth (public visitor accounts; Wagtail admin login is separate
# and keeps using django.contrib.auth directly via ModelBackend above).
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
# Mandatory: an unverified account cannot log in at all, so it can never do
# anything beyond the marketing page — there is no separate "verified" gate
# to enforce in views.
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_SUBJECT_PREFIX = "[Sites of Grace] "
# Merges the age-confirmation checkbox into allauth's generated signup form.
ACCOUNT_SIGNUP_FORM_CLASS = "pilgrims.forms.AgeConfirmationSignupForm"

# --- Outbound email ---------------------------------------------------------
# Real provider config lives entirely in the environment — no credentials in
# source control. dev.py overrides EMAIL_BACKEND back to the console backend
# unconditionally, so a developer with no SMTP env vars set still gets a
# working (printed) verification email.
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@sitesofgrace.com")
SERVER_EMAIL = os.environ.get("SERVER_EMAIL", DEFAULT_FROM_EMAIL)

# Every pilgrim-photo report emails this address with a direct link to the
# moderation queue. Falls back to DEFAULT_FROM_EMAIL rather than failing
# silently or hardcoding an address.
MODERATION_EMAIL = os.environ.get("MODERATION_EMAIL") or DEFAULT_FROM_EMAIL


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
]

STATICFILES_DIRS = [
    PROJECT_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "/static/"

MEDIA_ROOT = BASE_DIR / "media"
MEDIA_URL = "/media/"

# Default storage settings
# See https://docs.djangoproject.com/en/6.0/ref/settings/#std-setting-STORAGES
#
# Two separate Spaces buckets, both in sfo3, each with ITS OWN credentials —
# not one bucket with a private prefix. "default" (sitesofgrace-media2, CDN
# on) is the existing public CMS media bucket; "pilgrim_private"
# (sitesofgrace-pilgrims, CDN off) is a second bucket for private pilgrim
# photos, reachable only via SPACES_PRIVATE_KEY/SPACES_PRIVATE_SECRET — a
# DigitalOcean "Limited Access" key scoped to that one bucket, object-level
# operations only (no ListAllMyBuckets/HeadBucket/versioning/lifecycle/CORS/
# policy calls). Read here (not just in production.py) so it's usable from a
# dev machine too — presigned-URL signing is S3/Spaces-specific behavior a
# local FileSystemStorage can't stand in for, so verifying it means pointing
# dev at the real bucket via these same env vars (e.g. in the untracked
# sitesofgrace/settings/local.py). No credentials are hardcoded, logged, or
# committed.
SPACES_BUCKET = os.environ.get("SPACES_BUCKET", "")
SPACES_KEY = os.environ.get("SPACES_KEY", "")
SPACES_SECRET = os.environ.get("SPACES_SECRET", "")
SPACES_REGION = os.environ.get("SPACES_REGION", "")
SPACES_ENDPOINT_URL = os.environ.get("SPACES_ENDPOINT_URL", "")

SPACES_PRIVATE_BUCKET = os.environ.get("SPACES_PRIVATE_BUCKET", "")
SPACES_PRIVATE_KEY = os.environ.get("SPACES_PRIVATE_KEY", "")
SPACES_PRIVATE_SECRET = os.environ.get("SPACES_PRIVATE_SECRET", "")

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
    # A separate bucket (sitesofgrace-pilgrims) with a separate, narrowly-
    # scoped key — not just a private prefix on the public bucket. See
    # pilgrims/models.py:PilgrimPhoto and pilgrims/imaging.py. The whole
    # bucket is private, so no "location" prefix is needed.
    "pilgrim_private": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {
            "access_key": SPACES_PRIVATE_KEY,
            "secret_key": SPACES_PRIVATE_SECRET,
            "bucket_name": SPACES_PRIVATE_BUCKET,
            "region_name": SPACES_REGION,
            "endpoint_url": SPACES_ENDPOINT_URL,
            "default_acl": "private",
            "querystring_auth": True,
            "querystring_expire": 900,
            # Must stay None/False: a custom/CDN domain makes
            # S3Storage.url() return a bare, unsigned URL (it assumes the
            # CDN handles auth), which would silently defeat every
            # presigned-URL protection below — and this bucket has no CDN
            # anyway.
            "custom_domain": None,
            # True (not False, unlike "default"): every key here is
            # pilgrims/<owner-uuid>/<photo-uuid>/<field>.<ext> — a fresh
            # UUID per photo, so a real collision is not a real risk. This
            # is required, not just harmless: with file_overwrite=False,
            # Storage.save() calls .exists() (S3 HeadObject) before every
            # save to dodge a collision, and this bucket's scoped key has
            # no s3:ListBucket — DigitalOcean Spaces (like S3) answers
            # HeadObject on a KEY THAT DOESN'T EXIST with 403, not 404,
            # when the caller can't list the bucket, and django-storages
            # only treats 404 as "doesn't exist" (s3.py:exists()). Every
            # single upload would 403 on that pre-check. Confirmed live
            # against sitesofgrace-pilgrims — see the phase-3 report.
            "file_overwrite": True,
        },
    },
}

# Django sets a maximum of 1000 fields per form by default, but particularly complex page models
# can exceed this limit within Wagtail's page editor.
DATA_UPLOAD_MAX_NUMBER_FIELDS = 10_000


# Wagtail settings

WAGTAIL_SITE_NAME = "sitesofgrace"

# Search
# https://docs.wagtail.org/en/stable/topics/search/backends.html
WAGTAILSEARCH_BACKENDS = {
    "default": {
        "BACKEND": "wagtail.search.backends.database",
    }
}

# Base URL to use when referring to full URLs within the Wagtail admin backend -
# e.g. in notification emails. Don't include '/admin' or a trailing slash
WAGTAILADMIN_BASE_URL = "http://example.com"

# Allowed file extensions for documents in the document library.
# This can be omitted to allow all files, but note that this may present a security risk
# if untrusted users are allowed to upload files -
# see https://docs.wagtail.org/en/stable/advanced_topics/deploying.html#user-uploaded-files
WAGTAILDOCS_EXTENSIONS = ['csv', 'docx', 'key', 'odt', 'pdf', 'pptx', 'rtf', 'txt', 'xlsx', 'zip']

# Maximum upload size for documents in bytes.
WAGTAILDOCS_MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB
