# Generated by Django 6.0.7 on 2026-07-20 17:22

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaintPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('also_known_as', models.CharField(blank=True, max_length=255)),
                ('honorific_type', models.CharField(blank=True, max_length=255)),
                ('feast_day', models.CharField(blank=True, max_length=120)),
                ('born', models.CharField(blank=True, max_length=160)),
                ('died', models.CharField(blank=True, max_length=160)),
                ('canonized', models.CharField(blank=True, max_length=200)),
                ('patronage', models.TextField(blank=True)),
                ('significance', models.TextField(blank=True)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('source_url', models.URLField(blank=True)),
                ('source_note', models.CharField(blank=True, max_length=255)),
                ('data_status', models.CharField(blank=True, max_length=40)),
                ('editor_notes', models.TextField(blank=True)),
                ('portrait', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('topics', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='saints', to='catalog.topic')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SacredSitePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('category', models.CharField(choices=[('Marian Apparition', 'Marian Apparition'), ('Eucharistic Miracle', 'Eucharistic Miracle'), ('Saints & Tombs', 'Saints & Tombs'), ('Holy Land', 'Holy Land'), ('Shrine & Basilica', 'Shrine & Basilica')], max_length=40)),
                ('canonical_status', models.CharField(blank=True, choices=[('Nihil obstat', 'Nihil obstat'), ('Prae oculis habeatur', 'Prae oculis habeatur'), ('Curatur', 'Curatur'), ('Sub mandato', 'Sub mandato'), ('Prohibetur', 'Prohibetur'), ('Declaratio de non supernaturalitate', 'Declaratio de non supernaturalitate')], max_length=60)),
                ('locality', models.CharField(blank=True, max_length=160)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('date_display', models.CharField(blank=True, max_length=160)),
                ('feast_day', models.CharField(blank=True, max_length=120)),
                ('summary_short', models.TextField(blank=True)),
                ('the_story', wagtail.fields.RichTextField(blank=True)),
                ('church_recognition', wagtail.fields.RichTextField(blank=True)),
                ('catholic_teaching', wagtail.fields.RichTextField(blank=True)),
                ('pilgrimage_info', wagtail.fields.RichTextField(blank=True)),
                ('go_deeper', wagtail.fields.RichTextField(blank=True)),
                ('location_link', models.URLField(blank=True)),
                ('notes_internal', models.TextField(blank=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('associated_saint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='catalog.saintpage')),
                ('topics', modelcluster.fields.ParentalManyToManyField(blank=True, related_name='sites', to='catalog.topic')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
