# Generated by Django 6.0.7 on 2026-07-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sacredsitepage',
            name='canonical_status',
            field=models.CharField(blank=True, choices=[('Nihil obstat', 'Nihil obstat'), ('Prae oculis habeatur', 'Prae oculis habeatur'), ('Curatur', 'Curatur'), ('Sub mandato', 'Sub mandato'), ('Prohibetur', 'Prohibetur'), ('Declaratio de non supernaturalitate', 'Declaratio de non supernaturalitate'), ('Not Applicable', 'Not Applicable'), ('Recognized Devotion', 'Recognized Devotion'), ('Constat de supernaturalitate (legacy)', 'Constat de supernaturalitate (legacy)')], max_length=60),
        ),
    ]
