# Generated by Django 6.0.7 on 2026-09-03 03:22

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_sacredsitepage_canonical_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="sacredsitepage",
            name="quick_accessibility",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="sacredsitepage",
            name="quick_accessibility_note",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sacredsitepage",
            name="quick_airport",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sacredsitepage",
            name="quick_airport_note",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sacredsitepage",
            name="quick_best_months",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="sacredsitepage",
            name="quick_best_months_note",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sacredsitepage",
            name="quick_ideal_stay",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="sacredsitepage",
            name="quick_ideal_stay_note",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sacredsitepage",
            name="quick_language",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="sacredsitepage",
            name="quick_language_note",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name="SiteTravelSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("how-long-should-i-stay", "How Long Should I Stay?"),
                            ("best-time-to-visit", "Best Time to Visit"),
                            ("getting-there", "Getting There From the United States"),
                            ("getting-around", "Getting Around"),
                            ("where-to-stay", "Where to Stay"),
                            ("accessibility", "Accessibility"),
                            ("most-important-things", "Most Important Things to Do"),
                            ("suggested-itinerary", "Suggested Pilgrimage Itinerary"),
                            ("mass-confession-prayer", "Mass, Confession & Prayer"),
                            ("what-to-bring", "What to Bring"),
                            ("before-you-go", "Before You Go"),
                            ("additional-information", "Additional Information"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "teaser",
                    models.CharField(
                        blank=True,
                        help_text="One line under the heading, readable while the panel is closed.",
                        max_length=90,
                    ),
                ),
                ("body", wagtail.fields.RichTextField()),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_sections",
                        to="catalog.sacredsitepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
                "constraints": [
                    models.UniqueConstraint(
                        fields=("page", "kind"), name="unique_travel_section_per_page"
                    )
                ],
            },
        ),
    ]
