# Generated by Django 6.0.7 on 2026-09-04 03:50

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_migrate_pilgrimage_info_to_travel_section"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="PilgrimageTrailPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "trail_type",
                    models.CharField(
                        choices=[
                            ("Walking route", "Walking route"),
                            ("Driving route", "Driving route"),
                            ("Mixed route", "Mixed route"),
                            ("Devotional route", "Devotional route"),
                        ],
                        default="Walking route",
                        max_length=40,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, help_text="e.g. Northern Spain", max_length=160
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, help_text="e.g. France & Spain", max_length=160
                    ),
                ),
                ("start_point", models.CharField(blank=True, max_length=160)),
                ("end_point", models.CharField(blank=True, max_length=160)),
                (
                    "length_display",
                    models.CharField(
                        blank=True, help_text='e.g. "490 miles / 790 km"', max_length=80
                    ),
                ),
                (
                    "duration_display",
                    models.CharField(
                        blank=True, help_text='e.g. "30-35 days on foot"', max_length=80
                    ),
                ),
                ("best_season", models.CharField(blank=True, max_length=80)),
                (
                    "waymarking",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Yellow arrows and scallop shells"',
                        max_length=80,
                    ),
                ),
                ("summary_short", models.TextField(blank=True)),
                ("the_story", wagtail.fields.RichTextField(blank=True)),
                ("church_recognition", wagtail.fields.RichTextField(blank=True)),
                ("catholic_teaching", wagtail.fields.RichTextField(blank=True)),
                ("walking_the_route", wagtail.fields.RichTextField(blank=True)),
                ("go_deeper", wagtail.fields.RichTextField(blank=True)),
                (
                    "line_color",
                    models.CharField(
                        choices=[
                            ("gold", "Gold"),
                            ("navy", "Navy"),
                            ("slate", "Slate blue"),
                            ("terracotta", "Terracotta"),
                            ("olive", "Olive"),
                            ("plum", "Plum"),
                        ],
                        default="gold",
                        help_text="Color of this trail's line on the interactive map.",
                        max_length=20,
                    ),
                ),
                ("official_url", models.URLField(blank=True)),
                ("notes_internal", models.TextField(blank=True)),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "topics",
                    modelcluster.fields.ParentalManyToManyField(
                        blank=True, related_name="trails", to="catalog.topic"
                    ),
                ),
            ],
            options={
                "verbose_name": "Pilgrimage trail page",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="TrailStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "waypoint_name",
                    models.CharField(
                        blank=True,
                        help_text="Only for a stop with no page of its own yet. Ignored when a site page is chosen.",
                        max_length=160,
                    ),
                ),
                ("waypoint_locality", models.CharField(blank=True, max_length=160)),
                (
                    "waypoint_latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "waypoint_longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="One line on why this stop matters, shown in the stop list and map popup.",
                        max_length=300,
                    ),
                ),
                (
                    "distance_display",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "288 km from the start"',
                        max_length=60,
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        help_text="Choose the sacred site page for this stop, if it has one.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trail_stops",
                        to="catalog.sacredsitepage",
                    ),
                ),
                (
                    "trail",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="catalog.pilgrimagetrailpage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
