# Generated by Django 6.0.7 on 2026-09-10 20:25

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_pilgrimagetrailpage_trailstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='sacredsitepage',
            name='related_saints',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Other saints connected to this site: the visionary of an apparition, companions, or the figure a Holy Land place belongs to. The principal saint goes in the field above.', related_name='related_sites', to='catalog.saintpage'),
        ),
        migrations.AlterField(
            model_name='sacredsitepage',
            name='associated_saint',
            field=models.ForeignKey(blank=True, help_text='The saint this site principally belongs to -- whose shrine or tomb it is, or Our Lady for an apparition site.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sites', to='catalog.saintpage'),
        ),
    ]
