# Generated by Django 6.0.7 on 2026-09-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_sacredsitepage_related_saints_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saintpage',
            name='burial_place',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='saintpage',
            name='portrait_credit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='saintpage',
            name='portrait_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='saintpage',
            name='religious_order',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='saintpage',
            name='wikidata_id',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
