# Generated by Django 6.0.7 on 2026-07-16 20:42

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('lede', models.TextField(blank=True, help_text='Short italic introduction shown under the title.')),
                ('closing_heading', models.CharField(blank=True, max_length=120)),
                ('closing_text', models.CharField(blank=True, max_length=255)),
                ('closing_cta_text', models.CharField(blank=True, max_length=40)),
                ('closing_cta_url', models.CharField(blank=True, help_text='Used only if no page is chosen.', max_length=255)),
                ('closing_cta_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'verbose_name': 'Learn page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LearnSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(max_length=160)),
                ('body', wagtail.fields.RichTextField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=80)),
                ('link_url', models.CharField(blank=True, help_text='Used only if no page is chosen.', max_length=255)),
                ('icon', models.ForeignKey(blank=True, help_text='Optional. A styled placeholder shows until an icon is added.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning.learnpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
