# Generated by Django 6.0.7 on 2026-07-27 18:51

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_alter_sacredsitepage_canonical_status'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculatorDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_party_size', models.PositiveIntegerField(default=2)),
                ('default_nights', models.PositiveIntegerField(default=5)),
                ('meals_per_day', models.PositiveIntegerField(default=3)),
                ('people_per_room', models.PositiveIntegerField(default=2)),
                ('hotel_tier_budget_multiplier', models.DecimalField(decimal_places=2, default=0.7, max_digits=4)),
                ('hotel_tier_midrange_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('hotel_tier_comfort_multiplier', models.DecimalField(decimal_places=2, default=1.6, max_digits=4)),
                ('misc_buffer_percent', models.PositiveIntegerField(default=12)),
                ('currency', models.CharField(default='USD', max_length=8)),
            ],
            options={
                'verbose_name': 'Trip calculator defaults',
            },
        ),
        migrations.CreateModel(
            name='RegionFlightAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('North America', 'North America'), ('Latin America', 'Latin America'), ('Western Europe', 'Western Europe'), ('Southern Europe', 'Southern Europe'), ('Ireland & UK', 'Ireland & UK'), ('Eastern Europe', 'Eastern Europe'), ('Holy Land', 'Holy Land')], max_length=40, unique=True)),
                ('avg_roundtrip_usd_from_us', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(choices=[('North America', 'North America'), ('Latin America', 'Latin America'), ('Western Europe', 'Western Europe'), ('Southern Europe', 'Southern Europe'), ('Ireland & UK', 'Ireland & UK'), ('Eastern Europe', 'Eastern Europe'), ('Holy Land', 'Holy Land')], max_length=40)),
                ('nearest_airport_iata', models.CharField(blank=True, max_length=8)),
                ('nearest_airport_name', models.CharField(blank=True, max_length=160)),
                ('hotel_night_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('meal_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('local_transport_day_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('taxi_typical_usd', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('associated_sites', models.ManyToManyField(blank=True, related_name='destination_costs', to='catalog.sacredsitepage')),
            ],
            options={
                'ordering': ['city'],
            },
        ),
        migrations.CreateModel(
            name='PlanPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('heading', models.CharField(blank=True, max_length=200)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('disclaimer', wagtail.fields.RichTextField(blank=True, default="<p>These numbers are estimates to help you plan, not a price quote. Real costs change with the season, how far ahead you book, and where you're traveling from. Use this as a starting point, then confirm prices before you book.</p>")),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
