# Generated by Django 6.0.7 on 2026-07-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculatordefaults',
            name='inter_destination_hop_usd',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=8),
        ),
    ]
